#!/usr/bin/env python3
"""Generate ssnail_tables_pkg.vhdl: the SiLU, GELU and exp tables, from the
SSNAIL tools' ssnail_hw.py, so the hardware uses exactly the emulator's
coefficients.  The output is a synthesis source: commit it.

    python3 gen_tables.py [--check]       (--check: exit 1 if out of date)
"""
import os
import sys
_here = os.path.dirname(os.path.abspath(__file__))
_tools = os.environ.get("SSNAIL_TOOLS")
if not _tools:
    for _c in (os.path.join(_here, "SSNAIL"), os.path.join(_here, "SSNAIL", "ssnail_tools")):
        if os.path.exists(os.path.join(_c, "ssnail_isa.py")):
            _tools = _c
            break
sys.path.insert(0, _tools or os.path.join(_here, "SSNAIL"))
import numpy as np
import ssnail_hw as H

OUT = os.path.join(os.getcwd(), "ssnail_tables_pkg.vhdl")


def bits(v):
    return int(np.asarray(v, dtype=np.float32).view(np.uint32))


def table(name, t):
    out = [f"  -- {name}: [{float(t.lo)}, {float(t.hi)}), y = c0[i] + c1[i] * x\n",
           f"  constant {name}_LO : unsigned(31 downto 0) := x\"{bits(t.lo):08X}\";\n",
           f"  constant {name}_HI : unsigned(31 downto 0) := x\"{bits(t.hi):08X}\";\n",
           f"  constant {name}_K  : unsigned(31 downto 0) := x\"{bits(t.k):08X}\";\n"]
    for c, arr in (("C0", t.c0), ("C1", t.c1)):
        out.append(f"  constant {name}_{c} : tab_t := (\n")
        out.append(",\n".join(f"    x\"{bits(v):08X}\"" for v in arr))
        out.append(");\n")
    return "".join(out)


text = ("-- GENERATED by gen_tables.py from the SSNAIL tools (ssnail_hw.py).\n"
        "-- Do not edit: regenerate.\n"
        "library ieee;\nuse ieee.std_logic_1164.all;\nuse ieee.numeric_std.all;\n\n"
        "package ssnail_tables_pkg is\n"
        f"  constant TAB_SEGMENTS : natural := {H.SEGMENTS};\n"
        f"  type tab_t is array (0 to {H.SEGMENTS - 1}) of unsigned(31 downto 0);\n\n"
        + table("SILU", H.SILU) + "\n" + table("GELU", H.GELU) + "\n" + table("EXPT", H.EXP)
        + "end package;\n")

if "--check" in sys.argv:
    cur = open(OUT).read() if os.path.exists(OUT) else ""
    if cur != text:
        print("ssnail_tables_pkg.vhdl is out of date with the SSNAIL tools: run gen_tables.py")
        sys.exit(1)
    print("ssnail_tables_pkg.vhdl is up to date")
else:
    open(OUT, "w").write(text)
    print(f"wrote {OUT} ({H.SEGMENTS} segments x 3 tables)")
