
####################################################################################
# Generated by PlanAhead 14.7 built on 'Fri Sep 27 19:24:36 MDT 2013' by 'xbuild'
####################################################################################


####################################################################################
# Constraints from file : 'mega65r1.ucf'
####################################################################################

## This file is a general .ucf for the Nexys4 DDR Rev C board
## To use it in a project:
## - uncomment the lines corresponding to used pins
## - rename the used signals according to the project

## Clock signal (100MHz)
set_property PACKAGE_PIN V13 [get_ports CLK_IN]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:7
# The conversion of 'IOSTANDARD' constraint on 'net' object 'CLK_IN' has been applied to the port object 'CLK_IN'.
set_property IOSTANDARD LVCMOS33 [get_ports CLK_IN]

# All timing constraint translations are rough conversions, intended to act as a template for further manual refinement. The translations should not be expected to produce semantically identical results to the original ucf. Each xdc timing constraint must be manually inspected and verified to ensure it captures the desired intent

# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:9
create_clock -name CLK_IN -period 10.000 [get_ports CLK_IN]

## Buttons
# XXX - Currently resets FPGA, rather than CPU
#
set_property PACKAGE_PIN AA18 [get_ports btnCpuReset]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:13
# The conversion of 'IOSTANDARD' constraint on 'net' object 'btnCpuReset' has been applied to the port object 'btnCpuReset'.
set_property IOSTANDARD LVCMOS33 [get_ports btnCpuReset]

# General purpose LED on mother board
set_property PACKAGE_PIN U22 [get_ports led]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:16
# The conversion of 'IOSTANDARD' constraint on 'net' object 'led' has been applied to the port object 'led'.
set_property IOSTANDARD LVCMOS33 [get_ports led]

# CBM-488/IEC serial port
#
set_property PACKAGE_PIN AA21 [get_ports iec_clk_en]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:19
# The conversion of 'IOSTANDARD' constraint on 'net' object 'iec_clk_en' has been applied to the port object 'iec_clk_en'.
set_property IOSTANDARD LVCMOS33 [get_ports iec_clk_en]
#
set_property PACKAGE_PIN Y21 [get_ports iec_data_en]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:20
# The conversion of 'IOSTANDARD' constraint on 'net' object 'iec_data_en' has been applied to the port object 'iec_data_en'.
set_property IOSTANDARD LVCMOS33 [get_ports iec_data_en]
#
set_property PACKAGE_PIN Y22 [get_ports iec_data_o]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:21
# The conversion of 'IOSTANDARD' constraint on 'net' object 'iec_data_o' has been applied to the port object 'iec_data_o'.
set_property IOSTANDARD LVCMOS33 [get_ports iec_data_o]
#
set_property PACKAGE_PIN AB21 [get_ports iec_reset]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:22
# The conversion of 'IOSTANDARD' constraint on 'net' object 'iec_reset' has been applied to the port object 'iec_reset'.
set_property IOSTANDARD LVCMOS33 [get_ports iec_reset]
#
set_property PACKAGE_PIN AB22 [get_ports iec_clk_o]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:23
# The conversion of 'IOSTANDARD' constraint on 'net' object 'iec_clk_o' has been applied to the port object 'iec_clk_o'.
set_property IOSTANDARD LVCMOS33 [get_ports iec_clk_o]
#
set_property PACKAGE_PIN W19 [get_ports iec_data_i]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:24
# The conversion of 'IOSTANDARD' constraint on 'net' object 'iec_data_i' has been applied to the port object 'iec_data_i'.
set_property IOSTANDARD LVCMOS33 [get_ports iec_data_i]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:24
# The conversion of 'DRIVE' constraint on 'net' object 'iec_data_i' has been applied to the port object 'iec_data_i'.
set_property DRIVE 24 [get_ports iec_data_i]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:24
# The conversion of 'PULL' constraint on 'net' object 'iec_data_i' has been applied to the port object 'iec_data_i'.
set_property PULLUP true [get_ports iec_data_i]
#
set_property PACKAGE_PIN Y19 [get_ports iec_clk_i]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:25
# The conversion of 'IOSTANDARD' constraint on 'net' object 'iec_clk_i' has been applied to the port object 'iec_clk_i'.
set_property IOSTANDARD LVCMOS33 [get_ports iec_clk_i]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:25
# The conversion of 'DRIVE' constraint on 'net' object 'iec_clk_i' has been applied to the port object 'iec_clk_i'.
set_property DRIVE 24 [get_ports iec_clk_i]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:25
# The conversion of 'PULL' constraint on 'net' object 'iec_clk_i' has been applied to the port object 'iec_clk_i'.
set_property PULLUP true [get_ports iec_clk_i]
#
set_property PACKAGE_PIN P14 [get_ports iec_atn]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:26
# The conversion of 'IOSTANDARD' constraint on 'net' object 'iec_atn' has been applied to the port object 'iec_atn'.
set_property IOSTANDARD LVCMOS33 [get_ports iec_atn]

# C64 Cartridge port control lines
# *_dir=1 means FPGA->Port, =0 means Port->FPGA
#  R/_W, ROMH, IO1, GAME, EXROM, IO2, ROML, BA
set_property PACKAGE_PIN Y18 [get_ports cart_ctrl_dir]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:30
# The conversion of 'IOSTANDARD' constraint on 'net' object 'cart_ctrl_dir' has been applied to the port object 'cart_ctrl_dir'.
set_property IOSTANDARD LVCMOS33 [get_ports cart_ctrl_dir]
# A15-8
set_property PACKAGE_PIN L19 [get_ports cart_haddr_dir]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:31
# The conversion of 'IOSTANDARD' constraint on 'net' object 'cart_haddr_dir' has been applied to the port object 'cart_haddr_dir'.
set_property IOSTANDARD LVCMOS33 [get_ports cart_haddr_dir]
# A7-0
set_property PACKAGE_PIN L20 [get_ports cart_laddr_dir]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:32
# The conversion of 'IOSTANDARD' constraint on 'net' object 'cart_laddr_dir' has been applied to the port object 'cart_laddr_dir'.
set_property IOSTANDARD LVCMOS33 [get_ports cart_laddr_dir]
# D7-D0
set_property PACKAGE_PIN W21 [get_ports cart_data_dir]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:33
# The conversion of 'IOSTANDARD' constraint on 'net' object 'cart_data_dir' has been applied to the port object 'cart_data_dir'.
set_property IOSTANDARD LVCMOS33 [get_ports cart_data_dir]
# A15-0
set_property PACKAGE_PIN K19 [get_ports cart_addr_en]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:34
# The conversion of 'IOSTANDARD' constraint on 'net' object 'cart_addr_en' has been applied to the port object 'cart_addr_en'.
set_property IOSTANDARD LVCMOS33 [get_ports cart_addr_en]
# D7-D0
set_property PACKAGE_PIN U18 [get_ports cart_data_en]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:35
# The conversion of 'IOSTANDARD' constraint on 'net' object 'cart_data_en' has been applied to the port object 'cart_data_en'.
set_property IOSTANDARD LVCMOS33 [get_ports cart_data_en]

# C64 Cartridge port
#  output only
set_property PACKAGE_PIN V22 [get_ports cart_phi2]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:38
# The conversion of 'IOSTANDARD' constraint on 'net' object 'cart_phi2' has been applied to the port object 'cart_phi2'.
set_property IOSTANDARD LVCMOS33 [get_ports cart_phi2]
# output only
set_property PACKAGE_PIN U21 [get_ports cart_dotclock]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:39
# The conversion of 'IOSTANDARD' constraint on 'net' object 'cart_dotclock' has been applied to the port object 'cart_dotclock'.
set_property IOSTANDARD LVCMOS33 [get_ports cart_dotclock]
# output only
set_property PACKAGE_PIN W22 [get_ports cart_reset]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:40
# The conversion of 'IOSTANDARD' constraint on 'net' object 'cart_reset' has been applied to the port object 'cart_reset'.
set_property IOSTANDARD LVCMOS33 [get_ports cart_reset]
# input only
set_property PACKAGE_PIN W20 [get_ports cart_nmi]
set_property IOSTANDARD LVCMOS33 [get_ports cart_nmi]
# input only
set_property PACKAGE_PIN V18 [get_ports cart_irq]
set_property IOSTANDARD LVCMOS33 [get_ports cart_irq]
# input only
set_property PACKAGE_PIN AB18 [get_ports cart_dma]
set_property IOSTANDARD LVCMOS33 [get_ports cart_dma]
# bidirectional
set_property PACKAGE_PIN R18 [get_ports cart_exrom]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:44
# The conversion of 'IOSTANDARD' constraint on 'net' object 'cart_exrom' has been applied to the port object 'cart_exrom'.
set_property IOSTANDARD LVCMOS33 [get_ports cart_exrom]
# bidirectional
set_property PACKAGE_PIN N15 [get_ports cart_ba]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:45
# The conversion of 'IOSTANDARD' constraint on 'net' object 'cart_ba' has been applied to the port object 'cart_ba'.
set_property IOSTANDARD LVCMOS33 [get_ports cart_ba]
# bidirectional
set_property PACKAGE_PIN AA19 [get_ports cart_rw]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:46
# The conversion of 'IOSTANDARD' constraint on 'net' object 'cart_rw' has been applied to the port object 'cart_rw'.
set_property IOSTANDARD LVCMOS33 [get_ports cart_rw]
# bidirectional
set_property PACKAGE_PIN R19 [get_ports cart_roml]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:47
# The conversion of 'IOSTANDARD' constraint on 'net' object 'cart_roml' has been applied to the port object 'cart_roml'.
set_property IOSTANDARD LVCMOS33 [get_ports cart_roml]
# bidirectional
set_property PACKAGE_PIN V17 [get_ports cart_romh]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:48
# The conversion of 'IOSTANDARD' constraint on 'net' object 'cart_romh' has been applied to the port object 'cart_romh'.
set_property IOSTANDARD LVCMOS33 [get_ports cart_romh]
# bidirectional
set_property PACKAGE_PIN W17 [get_ports cart_io1]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:49
# The conversion of 'IOSTANDARD' constraint on 'net' object 'cart_io1' has been applied to the port object 'cart_io1'.
set_property IOSTANDARD LVCMOS33 [get_ports cart_io1]
# bidirectional
set_property PACKAGE_PIN U17 [get_ports cart_game]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:50
# The conversion of 'IOSTANDARD' constraint on 'net' object 'cart_game' has been applied to the port object 'cart_game'.
set_property IOSTANDARD LVCMOS33 [get_ports cart_game]
# bidirectional
set_property PACKAGE_PIN T18 [get_ports cart_io2]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:51
# The conversion of 'IOSTANDARD' constraint on 'net' object 'cart_io2' has been applied to the port object 'cart_io2'.
set_property IOSTANDARD LVCMOS33 [get_ports cart_io2]
#
set_property PACKAGE_PIN N17 [get_ports {cart_d[7]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:52
# The conversion of 'IOSTANDARD' constraint on 'net' object 'cart_d[7]' has been applied to the port object 'cart_d[7]'.
set_property IOSTANDARD LVCMOS33 [get_ports {cart_d[7]}]
#
set_property PACKAGE_PIN P17 [get_ports {cart_d[6]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:53
# The conversion of 'IOSTANDARD' constraint on 'net' object 'cart_d[6]' has been applied to the port object 'cart_d[6]'.
set_property IOSTANDARD LVCMOS33 [get_ports {cart_d[6]}]
#
set_property PACKAGE_PIN P15 [get_ports {cart_d[5]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:54
# The conversion of 'IOSTANDARD' constraint on 'net' object 'cart_d[5]' has been applied to the port object 'cart_d[5]'.
set_property IOSTANDARD LVCMOS33 [get_ports {cart_d[5]}]
#
set_property PACKAGE_PIN R16 [get_ports {cart_d[4]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:55
# The conversion of 'IOSTANDARD' constraint on 'net' object 'cart_d[4]' has been applied to the port object 'cart_d[4]'.
set_property IOSTANDARD LVCMOS33 [get_ports {cart_d[4]}]
#
set_property PACKAGE_PIN N13 [get_ports {cart_d[3]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:56
# The conversion of 'IOSTANDARD' constraint on 'net' object 'cart_d[3]' has been applied to the port object 'cart_d[3]'.
set_property IOSTANDARD LVCMOS33 [get_ports {cart_d[3]}]
#
set_property PACKAGE_PIN N14 [get_ports {cart_d[2]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:57
# The conversion of 'IOSTANDARD' constraint on 'net' object 'cart_d[2]' has been applied to the port object 'cart_d[2]'.
set_property IOSTANDARD LVCMOS33 [get_ports {cart_d[2]}]
#
set_property PACKAGE_PIN P16 [get_ports {cart_d[1]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:58
# The conversion of 'IOSTANDARD' constraint on 'net' object 'cart_d[1]' has been applied to the port object 'cart_d[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {cart_d[1]}]
#
set_property PACKAGE_PIN R17 [get_ports {cart_d[0]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:59
# The conversion of 'IOSTANDARD' constraint on 'net' object 'cart_d[0]' has been applied to the port object 'cart_d[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {cart_d[0]}]
#
set_property PACKAGE_PIN G17 [get_ports {cart_a[15]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:60
# The conversion of 'IOSTANDARD' constraint on 'net' object 'cart_a[15]' has been applied to the port object 'cart_a[15]'.
set_property IOSTANDARD LVCMOS33 [get_ports {cart_a[15]}]
#
set_property PACKAGE_PIN G18 [get_ports {cart_a[14]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:61
# The conversion of 'IOSTANDARD' constraint on 'net' object 'cart_a[14]' has been applied to the port object 'cart_a[14]'.
set_property IOSTANDARD LVCMOS33 [get_ports {cart_a[14]}]
#
set_property PACKAGE_PIN J15 [get_ports {cart_a[13]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:62
# The conversion of 'IOSTANDARD' constraint on 'net' object 'cart_a[13]' has been applied to the port object 'cart_a[13]'.
set_property IOSTANDARD LVCMOS33 [get_ports {cart_a[13]}]
#
set_property PACKAGE_PIN H15 [get_ports {cart_a[12]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:63
# The conversion of 'IOSTANDARD' constraint on 'net' object 'cart_a[12]' has been applied to the port object 'cart_a[12]'.
set_property IOSTANDARD LVCMOS33 [get_ports {cart_a[12]}]
#
set_property PACKAGE_PIN H17 [get_ports {cart_a[11]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:64
# The conversion of 'IOSTANDARD' constraint on 'net' object 'cart_a[11]' has been applied to the port object 'cart_a[11]'.
set_property IOSTANDARD LVCMOS33 [get_ports {cart_a[11]}]
#
set_property PACKAGE_PIN H18 [get_ports {cart_a[10]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:65
# The conversion of 'IOSTANDARD' constraint on 'net' object 'cart_a[10]' has been applied to the port object 'cart_a[10]'.
set_property IOSTANDARD LVCMOS33 [get_ports {cart_a[10]}]
#
set_property PACKAGE_PIN M21 [get_ports {cart_a[9]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:66
# The conversion of 'IOSTANDARD' constraint on 'net' object 'cart_a[9]' has been applied to the port object 'cart_a[9]'.
set_property IOSTANDARD LVCMOS33 [get_ports {cart_a[9]}]
#
set_property PACKAGE_PIN L21 [get_ports {cart_a[8]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:67
# The conversion of 'IOSTANDARD' constraint on 'net' object 'cart_a[8]' has been applied to the port object 'cart_a[8]'.
set_property IOSTANDARD LVCMOS33 [get_ports {cart_a[8]}]
#
set_property PACKAGE_PIN K21 [get_ports {cart_a[7]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:68
# The conversion of 'IOSTANDARD' constraint on 'net' object 'cart_a[7]' has been applied to the port object 'cart_a[7]'.
set_property IOSTANDARD LVCMOS33 [get_ports {cart_a[7]}]
#
set_property PACKAGE_PIN G20 [get_ports {cart_a[6]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:69
# The conversion of 'IOSTANDARD' constraint on 'net' object 'cart_a[6]' has been applied to the port object 'cart_a[6]'.
set_property IOSTANDARD LVCMOS33 [get_ports {cart_a[6]}]
#
set_property PACKAGE_PIN H20 [get_ports {cart_a[5]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:70
# The conversion of 'IOSTANDARD' constraint on 'net' object 'cart_a[5]' has been applied to the port object 'cart_a[5]'.
set_property IOSTANDARD LVCMOS33 [get_ports {cart_a[5]}]
#
set_property PACKAGE_PIN J21 [get_ports {cart_a[4]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:71
# The conversion of 'IOSTANDARD' constraint on 'net' object 'cart_a[4]' has been applied to the port object 'cart_a[4]'.
set_property IOSTANDARD LVCMOS33 [get_ports {cart_a[4]}]
#
set_property PACKAGE_PIN J20 [get_ports {cart_a[3]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:72
# The conversion of 'IOSTANDARD' constraint on 'net' object 'cart_a[3]' has been applied to the port object 'cart_a[3]'.
set_property IOSTANDARD LVCMOS33 [get_ports {cart_a[3]}]
#
set_property PACKAGE_PIN K22 [get_ports {cart_a[2]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:73
# The conversion of 'IOSTANDARD' constraint on 'net' object 'cart_a[2]' has been applied to the port object 'cart_a[2]'.
set_property IOSTANDARD LVCMOS33 [get_ports {cart_a[2]}]
#
set_property PACKAGE_PIN H19 [get_ports {cart_a[1]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:74
# The conversion of 'IOSTANDARD' constraint on 'net' object 'cart_a[1]' has been applied to the port object 'cart_a[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {cart_a[1]}]
#
set_property PACKAGE_PIN K18 [get_ports {cart_a[0]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:75
# The conversion of 'IOSTANDARD' constraint on 'net' object 'cart_a[0]' has been applied to the port object 'cart_a[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {cart_a[0]}]



# C65 Keyboard
#
set_property PACKAGE_PIN M17 [get_ports restore_key]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:80
# The conversion of 'IOSTANDARD' constraint on 'net' object 'restore_key' has been applied to the port object 'restore_key'.
set_property IOSTANDARD LVCMOS33 [get_ports restore_key]
#	
set_property PACKAGE_PIN M18 [get_ports {column[0]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:81
# The conversion of 'IOSTANDARD' constraint on 'net' object 'column[0]' has been applied to the port object 'column[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {column[0]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:81
# The conversion of 'DRIVE' constraint on 'net' object 'column[0]' has been applied to the port object 'column[0]'.
set_property DRIVE 24 [get_ports {column[0]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:81
# The conversion of 'PULL' constraint on 'net' object 'column[0]' has been applied to the port object 'column[0]'.
set_property PULLUP true [get_ports {column[0]}]
#
set_property PACKAGE_PIN L18 [get_ports {column[1]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:82
# The conversion of 'IOSTANDARD' constraint on 'net' object 'column[1]' has been applied to the port object 'column[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {column[1]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:82
# The conversion of 'DRIVE' constraint on 'net' object 'column[1]' has been applied to the port object 'column[1]'.
set_property DRIVE 24 [get_ports {column[1]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:82
# The conversion of 'PULL' constraint on 'net' object 'column[1]' has been applied to the port object 'column[1]'.
set_property PULLUP true [get_ports {column[1]}]
#
set_property PACKAGE_PIN N18 [get_ports {column[2]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:83
# The conversion of 'IOSTANDARD' constraint on 'net' object 'column[2]' has been applied to the port object 'column[2]'.
set_property IOSTANDARD LVCMOS33 [get_ports {column[2]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:83
# The conversion of 'DRIVE' constraint on 'net' object 'column[2]' has been applied to the port object 'column[2]'.
set_property DRIVE 24 [get_ports {column[2]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:83
# The conversion of 'PULL' constraint on 'net' object 'column[2]' has been applied to the port object 'column[2]'.
set_property PULLUP true [get_ports {column[2]}]
#
set_property PACKAGE_PIN N19 [get_ports {column[3]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:84
# The conversion of 'IOSTANDARD' constraint on 'net' object 'column[3]' has been applied to the port object 'column[3]'.
set_property IOSTANDARD LVCMOS33 [get_ports {column[3]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:84
# The conversion of 'DRIVE' constraint on 'net' object 'column[3]' has been applied to the port object 'column[3]'.
set_property DRIVE 24 [get_ports {column[3]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:84
# The conversion of 'PULL' constraint on 'net' object 'column[3]' has been applied to the port object 'column[3]'.
set_property PULLUP true [get_ports {column[3]}]
#
set_property PACKAGE_PIN N20 [get_ports {column[4]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:85
# The conversion of 'IOSTANDARD' constraint on 'net' object 'column[4]' has been applied to the port object 'column[4]'.
set_property IOSTANDARD LVCMOS33 [get_ports {column[4]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:85
# The conversion of 'DRIVE' constraint on 'net' object 'column[4]' has been applied to the port object 'column[4]'.
set_property DRIVE 24 [get_ports {column[4]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:85
# The conversion of 'PULL' constraint on 'net' object 'column[4]' has been applied to the port object 'column[4]'.
set_property PULLUP true [get_ports {column[4]}]
#
set_property PACKAGE_PIN M20 [get_ports {column[5]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:86
# The conversion of 'IOSTANDARD' constraint on 'net' object 'column[5]' has been applied to the port object 'column[5]'.
set_property IOSTANDARD LVCMOS33 [get_ports {column[5]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:86
# The conversion of 'DRIVE' constraint on 'net' object 'column[5]' has been applied to the port object 'column[5]'.
set_property DRIVE 24 [get_ports {column[5]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:86
# The conversion of 'PULL' constraint on 'net' object 'column[5]' has been applied to the port object 'column[5]'.
set_property PULLUP true [get_ports {column[5]}]
#
set_property PACKAGE_PIN K13 [get_ports {column[6]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:87
# The conversion of 'IOSTANDARD' constraint on 'net' object 'column[6]' has been applied to the port object 'column[6]'.
set_property IOSTANDARD LVCMOS33 [get_ports {column[6]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:87
# The conversion of 'DRIVE' constraint on 'net' object 'column[6]' has been applied to the port object 'column[6]'.
set_property DRIVE 24 [get_ports {column[6]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:87
# The conversion of 'PULL' constraint on 'net' object 'column[6]' has been applied to the port object 'column[6]'.
set_property PULLUP true [get_ports {column[6]}]
#
set_property PACKAGE_PIN K14 [get_ports {column[7]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:88
# The conversion of 'IOSTANDARD' constraint on 'net' object 'column[7]' has been applied to the port object 'column[7]'.
set_property IOSTANDARD LVCMOS33 [get_ports {column[7]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:88
# The conversion of 'DRIVE' constraint on 'net' object 'column[7]' has been applied to the port object 'column[7]'.
set_property DRIVE 24 [get_ports {column[7]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:88
# The conversion of 'PULL' constraint on 'net' object 'column[7]' has been applied to the port object 'column[7]'.
set_property PULLUP true [get_ports {column[7]}]
#
set_property PACKAGE_PIN M13 [get_ports {column[8]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:89
# The conversion of 'IOSTANDARD' constraint on 'net' object 'column[8]' has been applied to the port object 'column[8]'.
set_property IOSTANDARD LVCMOS33 [get_ports {column[8]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:89
# The conversion of 'DRIVE' constraint on 'net' object 'column[8]' has been applied to the port object 'column[8]'.
set_property DRIVE 24 [get_ports {column[8]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:89
# The conversion of 'PULL' constraint on 'net' object 'column[8]' has been applied to the port object 'column[8]'.
set_property PULLUP true [get_ports {column[8]}]
#
set_property PACKAGE_PIN L13 [get_ports {row[8]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:90
# The conversion of 'IOSTANDARD' constraint on 'net' object 'row[8]' has been applied to the port object 'row[8]'.
set_property IOSTANDARD LVCMOS33 [get_ports {row[8]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:90
# The conversion of 'DRIVE' constraint on 'net' object 'row[8]' has been applied to the port object 'row[8]'.
set_property DRIVE 6 [get_ports {row[8]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:90
# The conversion of 'PULL' constraint on 'net' object 'row[8]' has been applied to the port object 'row[8]'.
set_property PULLUP true [get_ports {row[8]}]
#
set_property PACKAGE_PIN K17 [get_ports {row[7]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:91
# The conversion of 'IOSTANDARD' constraint on 'net' object 'row[7]' has been applied to the port object 'row[7]'.
set_property IOSTANDARD LVCMOS33 [get_ports {row[7]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:91
# The conversion of 'DRIVE' constraint on 'net' object 'row[7]' has been applied to the port object 'row[7]'.
set_property DRIVE 6 [get_ports {row[7]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:91
# The conversion of 'PULL' constraint on 'net' object 'row[7]' has been applied to the port object 'row[7]'.
set_property PULLUP true [get_ports {row[7]}]
#
set_property PACKAGE_PIN J17 [get_ports {row[6]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:92
# The conversion of 'IOSTANDARD' constraint on 'net' object 'row[6]' has been applied to the port object 'row[6]'.
set_property IOSTANDARD LVCMOS33 [get_ports {row[6]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:92
# The conversion of 'DRIVE' constraint on 'net' object 'row[6]' has been applied to the port object 'row[6]'.
set_property DRIVE 6 [get_ports {row[6]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:92
# The conversion of 'PULL' constraint on 'net' object 'row[6]' has been applied to the port object 'row[6]'.
set_property PULLUP true [get_ports {row[6]}]
#
set_property PACKAGE_PIN L14 [get_ports {row[5]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:93
# The conversion of 'IOSTANDARD' constraint on 'net' object 'row[5]' has been applied to the port object 'row[5]'.
set_property IOSTANDARD LVCMOS33 [get_ports {row[5]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:93
# The conversion of 'DRIVE' constraint on 'net' object 'row[5]' has been applied to the port object 'row[5]'.
set_property DRIVE 6 [get_ports {row[5]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:93
# The conversion of 'PULL' constraint on 'net' object 'row[5]' has been applied to the port object 'row[5]'.
set_property PULLUP true [get_ports {row[5]}]
#
set_property PACKAGE_PIN L15 [get_ports {row[4]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:94
# The conversion of 'IOSTANDARD' constraint on 'net' object 'row[4]' has been applied to the port object 'row[4]'.
set_property IOSTANDARD LVCMOS33 [get_ports {row[4]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:94
# The conversion of 'DRIVE' constraint on 'net' object 'row[4]' has been applied to the port object 'row[4]'.
set_property DRIVE 6 [get_ports {row[4]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:94
# The conversion of 'PULL' constraint on 'net' object 'row[4]' has been applied to the port object 'row[4]'.
set_property PULLUP true [get_ports {row[4]}]
#
set_property PACKAGE_PIN L16 [get_ports {row[3]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:95
# The conversion of 'IOSTANDARD' constraint on 'net' object 'row[3]' has been applied to the port object 'row[3]'.
set_property IOSTANDARD LVCMOS33 [get_ports {row[3]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:95
# The conversion of 'DRIVE' constraint on 'net' object 'row[3]' has been applied to the port object 'row[3]'.
set_property DRIVE 6 [get_ports {row[3]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:95
# The conversion of 'PULL' constraint on 'net' object 'row[3]' has been applied to the port object 'row[3]'.
set_property PULLUP true [get_ports {row[3]}]
#
set_property PACKAGE_PIN K16 [get_ports {row[2]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:96
# The conversion of 'IOSTANDARD' constraint on 'net' object 'row[2]' has been applied to the port object 'row[2]'.
set_property IOSTANDARD LVCMOS33 [get_ports {row[2]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:96
# The conversion of 'DRIVE' constraint on 'net' object 'row[2]' has been applied to the port object 'row[2]'.
set_property DRIVE 6 [get_ports {row[2]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:96
# The conversion of 'PULL' constraint on 'net' object 'row[2]' has been applied to the port object 'row[2]'.
set_property PULLUP true [get_ports {row[2]}]
#
set_property PACKAGE_PIN M15 [get_ports {row[1]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:97
# The conversion of 'IOSTANDARD' constraint on 'net' object 'row[1]' has been applied to the port object 'row[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {row[1]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:97
# The conversion of 'DRIVE' constraint on 'net' object 'row[1]' has been applied to the port object 'row[1]'.
set_property DRIVE 6 [get_ports {row[1]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:97
# The conversion of 'PULL' constraint on 'net' object 'row[1]' has been applied to the port object 'row[1]'.
set_property PULLUP true [get_ports {row[1]}]
#
set_property PACKAGE_PIN M16 [get_ports {row[0]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:98
# The conversion of 'IOSTANDARD' constraint on 'net' object 'row[0]' has been applied to the port object 'row[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {row[0]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:98
# The conversion of 'DRIVE' constraint on 'net' object 'row[0]' has been applied to the port object 'row[0]'.
set_property DRIVE 6 [get_ports {row[0]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:98
# The conversion of 'PULL' constraint on 'net' object 'row[0]' has been applied to the port object 'row[0]'.
set_property PULLUP true [get_ports {row[0]}]
#
set_property PACKAGE_PIN N22 [get_ports keyleft]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:99
# The conversion of 'IOSTANDARD' constraint on 'net' object 'keyleft' has been applied to the port object 'keyleft'.
set_property IOSTANDARD LVCMOS33 [get_ports keyleft]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:99
# The conversion of 'PULL' constraint on 'net' object 'keyleft' has been applied to the port object 'keyleft'.
set_property PULLDOWN true [get_ports keyleft]
#
set_property PACKAGE_PIN M22 [get_ports keyup]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:100
# The conversion of 'IOSTANDARD' constraint on 'net' object 'keyup' has been applied to the port object 'keyup'.
set_property IOSTANDARD LVCMOS33 [get_ports keyup]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:100
# The conversion of 'PULL' constraint on 'net' object 'keyup' has been applied to the port object 'keyup'.
set_property PULLDOWN true [get_ports keyup]

# Joystick port A
set_property PACKAGE_PIN F16 [get_ports fa_down]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:103
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fa_down' has been applied to the port object 'fa_down'.
set_property IOSTANDARD LVCMOS33 [get_ports fa_down]
set_property PACKAGE_PIN C14 [get_ports fa_up]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:104
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fa_up' has been applied to the port object 'fa_up'.
set_property IOSTANDARD LVCMOS33 [get_ports fa_up]
set_property PACKAGE_PIN F14 [get_ports fa_left]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:105
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fa_left' has been applied to the port object 'fa_left'.
set_property IOSTANDARD LVCMOS33 [get_ports fa_left]
set_property PACKAGE_PIN F13 [get_ports fa_right]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:106
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fa_right' has been applied to the port object 'fa_right'.
set_property IOSTANDARD LVCMOS33 [get_ports fa_right]
set_property PACKAGE_PIN E17 [get_ports fa_fire]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:107
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fa_fire' has been applied to the port object 'fa_fire'.
set_property IOSTANDARD LVCMOS33 [get_ports fa_fire]

# Joystick port B
set_property PACKAGE_PIN P20 [get_ports fb_down]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:110
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fb_down' has been applied to the port object 'fb_down'.
set_property IOSTANDARD LVCMOS33 [get_ports fb_down]
set_property PACKAGE_PIN AA20 [get_ports fb_up]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:111
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fb_up' has been applied to the port object 'fb_up'.
set_property IOSTANDARD LVCMOS33 [get_ports fb_up]
set_property PACKAGE_PIN F21 [get_ports fb_left]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:112
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fb_left' has been applied to the port object 'fb_left'.
set_property IOSTANDARD LVCMOS33 [get_ports fb_left]
set_property PACKAGE_PIN F15 [get_ports fb_right]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:113
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fb_right' has been applied to the port object 'fb_right'.
set_property IOSTANDARD LVCMOS33 [get_ports fb_right]
set_property PACKAGE_PIN C15 [get_ports fb_fire]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:114
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fb_fire' has been applied to the port object 'fb_fire'.
set_property IOSTANDARD LVCMOS33 [get_ports fb_fire]

##VGA Connector

# XXX - Is this needed?
set_property PACKAGE_PIN AA9 [get_ports vdac_clk]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:119
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vdac_clk' has been applied to the port object 'vdac_clk'.
set_property IOSTANDARD LVCMOS33 [get_ports vdac_clk]
set_property PACKAGE_PIN V10 [get_ports vdac_sync_n]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:120
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vdac_sync_n' has been applied to the port object 'vdac_sync_n'.
set_property IOSTANDARD LVCMOS33 [get_ports vdac_sync_n]
set_property PACKAGE_PIN W11 [get_ports vdac_blank_n]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:121
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vdac_blank_n' has been applied to the port object 'vdac_blank_n'.
set_property IOSTANDARD LVCMOS33 [get_ports vdac_blank_n]

#
set_property PACKAGE_PIN U15 [get_ports {vgared[0]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:123
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vgared[0]' has been applied to the port object 'vgared[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vgared[0]}]
#
set_property PACKAGE_PIN V15 [get_ports {vgared[1]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:124
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vgared[1]' has been applied to the port object 'vgared[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vgared[1]}]
#
set_property PACKAGE_PIN T14 [get_ports {vgared[2]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:125
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vgared[2]' has been applied to the port object 'vgared[2]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vgared[2]}]
#IO_0_13
set_property PACKAGE_PIN Y17 [get_ports {vgared[3]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:126
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vgared[3]' has been applied to the port object 'vgared[3]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vgared[3]}]
#IO_L1P_T0_13
set_property PACKAGE_PIN Y16 [get_ports {vgared[4]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:127
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vgared[4]' has been applied to the port object 'vgared[4]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vgared[4]}]
#IO_L2N_T0_13
set_property PACKAGE_PIN AB17 [get_ports {vgared[5]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:128
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vgared[5]' has been applied to the port object 'vgared[5]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vgared[5]}]
#IO_L1N_T0_13
set_property PACKAGE_PIN AA16 [get_ports {vgared[6]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:129
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vgared[6]' has been applied to the port object 'vgared[6]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vgared[6]}]
#IO_L2P_T0_13
set_property PACKAGE_PIN AB16 [get_ports {vgared[7]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:130
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vgared[7]' has been applied to the port object 'vgared[7]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vgared[7]}]

#
set_property PACKAGE_PIN Y14 [get_ports {vgagreen[0]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:132
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vgagreen[0]' has been applied to the port object 'vgagreen[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vgagreen[0]}]
#
set_property PACKAGE_PIN W14 [get_ports {vgagreen[1]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:133
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vgagreen[1]' has been applied to the port object 'vgagreen[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vgagreen[1]}]
#IO_L4P_T0_13
set_property PACKAGE_PIN AA15 [get_ports {vgagreen[2]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:134
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vgagreen[2]' has been applied to the port object 'vgagreen[2]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vgagreen[2]}]
#IO_L4N_T0_13
set_property PACKAGE_PIN AB15 [get_ports {vgagreen[3]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:135
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vgagreen[3]' has been applied to the port object 'vgagreen[3]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vgagreen[3]}]
#
set_property PACKAGE_PIN Y13 [get_ports {vgagreen[4]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:136
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vgagreen[4]' has been applied to the port object 'vgagreen[4]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vgagreen[4]}]
#
set_property PACKAGE_PIN AA14 [get_ports {vgagreen[5]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:137
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vgagreen[5]' has been applied to the port object 'vgagreen[5]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vgagreen[5]}]
#IO_L3P_T0_DQS_13
set_property PACKAGE_PIN AA13 [get_ports {vgagreen[6]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:138
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vgagreen[6]' has been applied to the port object 'vgagreen[6]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vgagreen[6]}]
#IO_L3N_T0_DQS_13
set_property PACKAGE_PIN AB13 [get_ports {vgagreen[7]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:139
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vgagreen[7]' has been applied to the port object 'vgagreen[7]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vgagreen[7]}]

#
set_property PACKAGE_PIN W10 [get_ports {vgablue[0]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:141
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vgablue[0]' has been applied to the port object 'vgablue[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vgablue[0]}]
#
set_property PACKAGE_PIN Y12 [get_ports {vgablue[1]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:142
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vgablue[1]' has been applied to the port object 'vgablue[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vgablue[1]}]
#
set_property PACKAGE_PIN AB12 [get_ports {vgablue[2]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:143
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vgablue[2]' has been applied to the port object 'vgablue[2]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vgablue[2]}]
#
set_property PACKAGE_PIN AA11 [get_ports {vgablue[3]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:144
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vgablue[3]' has been applied to the port object 'vgablue[3]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vgablue[3]}]
#
set_property PACKAGE_PIN AB11 [get_ports {vgablue[4]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:145
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vgablue[4]' has been applied to the port object 'vgablue[4]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vgablue[4]}]
#
set_property PACKAGE_PIN Y11 [get_ports {vgablue[5]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:146
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vgablue[5]' has been applied to the port object 'vgablue[5]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vgablue[5]}]
#
set_property PACKAGE_PIN AB10 [get_ports {vgablue[6]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:147
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vgablue[6]' has been applied to the port object 'vgablue[6]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vgablue[6]}]
#
set_property PACKAGE_PIN AA10 [get_ports {vgablue[7]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:148
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vgablue[7]' has been applied to the port object 'vgablue[7]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vgablue[7]}]

#
set_property PACKAGE_PIN W12 [get_ports hsync]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:150
# The conversion of 'IOSTANDARD' constraint on 'net' object 'hsync' has been applied to the port object 'hsync'.
set_property IOSTANDARD LVCMOS33 [get_ports hsync]
#
set_property PACKAGE_PIN V14 [get_ports vsync]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:151
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vsync' has been applied to the port object 'vsync'.
set_property IOSTANDARD LVCMOS33 [get_ports vsync]

# HDMI output
#
set_property PACKAGE_PIN T3 [get_ports hdmi_scl]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:154
# The conversion of 'IOSTANDARD' constraint on 'net' object 'hdmi_scl' has been applied to the port object 'hdmi_scl'.
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_scl]
#
set_property PACKAGE_PIN U7 [get_ports hdmi_sda]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:155
# The conversion of 'IOSTANDARD' constraint on 'net' object 'hdmi_sda' has been applied to the port object 'hdmi_sda'.
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_sda]

#
set_property PACKAGE_PIN T6 [get_ports {hdmired[0]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:157
# The conversion of 'IOSTANDARD' constraint on 'net' object 'hdmired[0]' has been applied to the port object 'hdmired[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {hdmired[0]}]
#
set_property PACKAGE_PIN U1 [get_ports {hdmired[1]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:158
# The conversion of 'IOSTANDARD' constraint on 'net' object 'hdmired[1]' has been applied to the port object 'hdmired[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {hdmired[1]}]
#
set_property PACKAGE_PIN U5 [get_ports {hdmired[2]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:159
# The conversion of 'IOSTANDARD' constraint on 'net' object 'hdmired[2]' has been applied to the port object 'hdmired[2]'.
set_property IOSTANDARD LVCMOS33 [get_ports {hdmired[2]}]
#IO_0_13
set_property PACKAGE_PIN U6 [get_ports {hdmired[3]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:160
# The conversion of 'IOSTANDARD' constraint on 'net' object 'hdmired[3]' has been applied to the port object 'hdmired[3]'.
set_property IOSTANDARD LVCMOS33 [get_ports {hdmired[3]}]
#IO_L1P_T0_13
set_property PACKAGE_PIN U2 [get_ports {hdmired[4]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:161
# The conversion of 'IOSTANDARD' constraint on 'net' object 'hdmired[4]' has been applied to the port object 'hdmired[4]'.
set_property IOSTANDARD LVCMOS33 [get_ports {hdmired[4]}]
#IO_L2N_T0_13
set_property PACKAGE_PIN U3 [get_ports {hdmired[5]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:162
# The conversion of 'IOSTANDARD' constraint on 'net' object 'hdmired[5]' has been applied to the port object 'hdmired[5]'.
set_property IOSTANDARD LVCMOS33 [get_ports {hdmired[5]}]
#IO_L1N_T0_13
set_property PACKAGE_PIN V4 [get_ports {hdmired[6]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:163
# The conversion of 'IOSTANDARD' constraint on 'net' object 'hdmired[6]' has been applied to the port object 'hdmired[6]'.
set_property IOSTANDARD LVCMOS33 [get_ports {hdmired[6]}]
#IO_L2P_T0_13
set_property PACKAGE_PIN V2 [get_ports {hdmired[7]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:164
# The conversion of 'IOSTANDARD' constraint on 'net' object 'hdmired[7]' has been applied to the port object 'hdmired[7]'.
set_property IOSTANDARD LVCMOS33 [get_ports {hdmired[7]}]

#
set_property PACKAGE_PIN Y1 [get_ports {hdmigreen[0]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:166
# The conversion of 'IOSTANDARD' constraint on 'net' object 'hdmigreen[0]' has been applied to the port object 'hdmigreen[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {hdmigreen[0]}]
#
set_property PACKAGE_PIN Y3 [get_ports {hdmigreen[1]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:167
# The conversion of 'IOSTANDARD' constraint on 'net' object 'hdmigreen[1]' has been applied to the port object 'hdmigreen[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {hdmigreen[1]}]
#IO_L4P_T0_13
set_property PACKAGE_PIN W4 [get_ports {hdmigreen[2]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:168
# The conversion of 'IOSTANDARD' constraint on 'net' object 'hdmigreen[2]' has been applied to the port object 'hdmigreen[2]'.
set_property IOSTANDARD LVCMOS33 [get_ports {hdmigreen[2]}]
#IO_L4N_T0_13
set_property PACKAGE_PIN W5 [get_ports {hdmigreen[3]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:169
# The conversion of 'IOSTANDARD' constraint on 'net' object 'hdmigreen[3]' has been applied to the port object 'hdmigreen[3]'.
set_property IOSTANDARD LVCMOS33 [get_ports {hdmigreen[3]}]
#
set_property PACKAGE_PIN V7 [get_ports {hdmigreen[4]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:170
# The conversion of 'IOSTANDARD' constraint on 'net' object 'hdmigreen[4]' has been applied to the port object 'hdmigreen[4]'.
set_property IOSTANDARD LVCMOS33 [get_ports {hdmigreen[4]}]
#
set_property PACKAGE_PIN V8 [get_ports {hdmigreen[5]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:171
# The conversion of 'IOSTANDARD' constraint on 'net' object 'hdmigreen[5]' has been applied to the port object 'hdmigreen[5]'.
set_property IOSTANDARD LVCMOS33 [get_ports {hdmigreen[5]}]
#IO_L3P_T0_DQS_13
set_property PACKAGE_PIN AB1 [get_ports {hdmigreen[6]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:172
# The conversion of 'IOSTANDARD' constraint on 'net' object 'hdmigreen[6]' has been applied to the port object 'hdmigreen[6]'.
set_property IOSTANDARD LVCMOS33 [get_ports {hdmigreen[6]}]
#IO_L3N_T0_DQS_13
set_property PACKAGE_PIN W6 [get_ports {hdmigreen[7]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:173
# The conversion of 'IOSTANDARD' constraint on 'net' object 'hdmigreen[7]' has been applied to the port object 'hdmigreen[7]'.
set_property IOSTANDARD LVCMOS33 [get_ports {hdmigreen[7]}]

#
set_property PACKAGE_PIN AB3 [get_ports {hdmiblue[0]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:175
# The conversion of 'IOSTANDARD' constraint on 'net' object 'hdmiblue[0]' has been applied to the port object 'hdmiblue[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {hdmiblue[0]}]
#
set_property PACKAGE_PIN Y4 [get_ports {hdmiblue[1]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:176
# The conversion of 'IOSTANDARD' constraint on 'net' object 'hdmiblue[1]' has been applied to the port object 'hdmiblue[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {hdmiblue[1]}]
#
set_property PACKAGE_PIN AA4 [get_ports {hdmiblue[2]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:177
# The conversion of 'IOSTANDARD' constraint on 'net' object 'hdmiblue[2]' has been applied to the port object 'hdmiblue[2]'.
set_property IOSTANDARD LVCMOS33 [get_ports {hdmiblue[2]}]
#
set_property PACKAGE_PIN AA5 [get_ports {hdmiblue[3]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:178
# The conversion of 'IOSTANDARD' constraint on 'net' object 'hdmiblue[3]' has been applied to the port object 'hdmiblue[3]'.
set_property IOSTANDARD LVCMOS33 [get_ports {hdmiblue[3]}]
#
set_property PACKAGE_PIN AB5 [get_ports {hdmiblue[4]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:179
# The conversion of 'IOSTANDARD' constraint on 'net' object 'hdmiblue[4]' has been applied to the port object 'hdmiblue[4]'.
set_property IOSTANDARD LVCMOS33 [get_ports {hdmiblue[4]}]
#
set_property PACKAGE_PIN Y6 [get_ports {hdmiblue[5]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:180
# The conversion of 'IOSTANDARD' constraint on 'net' object 'hdmiblue[5]' has been applied to the port object 'hdmiblue[5]'.
set_property IOSTANDARD LVCMOS33 [get_ports {hdmiblue[5]}]
#
set_property PACKAGE_PIN AA6 [get_ports {hdmiblue[6]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:181
# The conversion of 'IOSTANDARD' constraint on 'net' object 'hdmiblue[6]' has been applied to the port object 'hdmiblue[6]'.
set_property IOSTANDARD LVCMOS33 [get_ports {hdmiblue[6]}]
#
set_property PACKAGE_PIN AB6 [get_ports {hdmiblue[7]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:182
# The conversion of 'IOSTANDARD' constraint on 'net' object 'hdmiblue[7]' has been applied to the port object 'hdmiblue[7]'.
set_property IOSTANDARD LVCMOS33 [get_ports {hdmiblue[7]}]

# XXX - We may need to tell the HDMI driver to set the appropriate operating mode
# XXX - We may need to provide a Data Enable signal to tell the HDMI driver when pixels are drawing
#
set_property PACKAGE_PIN R4 [get_ports hdmi_hsync]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:186
# The conversion of 'IOSTANDARD' constraint on 'net' object 'hdmi_hsync' has been applied to the port object 'hdmi_hsync'.
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_hsync]
#
set_property PACKAGE_PIN R6 [get_ports hdmi_vsync]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:187
# The conversion of 'IOSTANDARD' constraint on 'net' object 'hdmi_vsync' has been applied to the port object 'hdmi_vsync'.
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_vsync]
# Data Enable
set_property PACKAGE_PIN R2 [get_ports hdmi_de]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:188
# The conversion of 'IOSTANDARD' constraint on 'net' object 'hdmi_de' has been applied to the port object 'hdmi_de'.
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_de]

set_property PACKAGE_PIN AA1 [get_ports hdmi_spdif]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_spdif]
set_property PACKAGE_PIN AA8 [get_ports hdmi_spdif_out]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:191
# The conversion of 'IOSTANDARD' constraint on 'net' object 'hdmi_spdif_out' has been applied to the port object 'hdmi_spdif_out'.
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_spdif_out]

# PWM Audio
#
set_property PACKAGE_PIN L6 [get_ports pwm_l]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:194
# The conversion of 'IOSTANDARD' constraint on 'net' object 'pwm_l' has been applied to the port object 'pwm_l'.
set_property IOSTANDARD LVCMOS33 [get_ports pwm_l]
#
set_property PACKAGE_PIN F4 [get_ports pwm_r]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:195
# The conversion of 'IOSTANDARD' constraint on 'net' object 'pwm_r' has been applied to the port object 'pwm_r'.
set_property IOSTANDARD LVCMOS33 [get_ports pwm_r]

##USB HID (PS/2)
# XXX - Not currently wired on the first prototypes: May break this out on a PMOD or expansion header?
#NET "PS2Clk"        LOC= | IOSTANDARD=LVCMOS33; #
#NET "PS2Data"       LOC= | IOSTANDARD=LVCMOS33; #

##Quad SPI Flash
#NET "QspiCSn"       LOC= | IOSTANDARD=LVCMOS33; #
#NET "QspiDB<0>"     LOC= | IOSTANDARD=LVCMOS33; #
#NET "QspiDB<1>"     LOC= | IOSTANDARD=LVCMOS33; #
#NET "QspiDB<2>"     LOC= | IOSTANDARD=LVCMOS33; #
#NET "QspiDB<3>"     LOC= | IOSTANDARD=LVCMOS33; #

##SMSC Ethernet PHY
#
set_property PACKAGE_PIN P4 [get_ports {eth_rxd[0]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:210
# The conversion of 'IOSTANDARD' constraint on 'net' object 'eth_rxd[0]' has been applied to the port object 'eth_rxd[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {eth_rxd[0]}]
#
set_property PACKAGE_PIN L1 [get_ports {eth_rxd[1]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:211
# The conversion of 'IOSTANDARD' constraint on 'net' object 'eth_rxd[1]' has been applied to the port object 'eth_rxd[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {eth_rxd[1]}]
#
set_property PACKAGE_PIN L3 [get_ports {eth_txd[0]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:212
# The conversion of 'IOSTANDARD' constraint on 'net' object 'eth_txd[0]' has been applied to the port object 'eth_txd[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {eth_txd[0]}]
#
set_property PACKAGE_PIN K3 [get_ports {eth_txd[1]}]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:213
# The conversion of 'IOSTANDARD' constraint on 'net' object 'eth_txd[1]' has been applied to the port object 'eth_txd[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {eth_txd[1]}]
#
set_property PACKAGE_PIN K4 [get_ports eth_rxdv]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:214
# The conversion of 'IOSTANDARD' constraint on 'net' object 'eth_rxdv' has been applied to the port object 'eth_rxdv'.
set_property IOSTANDARD LVCMOS33 [get_ports eth_rxdv]
#NET "eth_Interrupt"  LOC= | IOSTANDARD=LVCMOS33; #
#
set_property PACKAGE_PIN J6 [get_ports eth_mdc]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:216
# The conversion of 'IOSTANDARD' constraint on 'net' object 'eth_mdc' has been applied to the port object 'eth_mdc'.
set_property IOSTANDARD LVCMOS33 [get_ports eth_mdc]
#
set_property PACKAGE_PIN L5 [get_ports eth_mdio]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:217
# The conversion of 'IOSTANDARD' constraint on 'net' object 'eth_mdio' has been applied to the port object 'eth_mdio'.
set_property IOSTANDARD LVCMOS33 [get_ports eth_mdio]
#
set_property PACKAGE_PIN L4 [get_ports eth_clock]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:218
# The conversion of 'IOSTANDARD' constraint on 'net' object 'eth_clock' has been applied to the port object 'eth_clock'.
set_property IOSTANDARD LVCMOS33 [get_ports eth_clock]
#
set_property PACKAGE_PIN K6 [get_ports eth_reset]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:219
# The conversion of 'IOSTANDARD' constraint on 'net' object 'eth_reset' has been applied to the port object 'eth_reset'.
set_property IOSTANDARD LVCMOS33 [get_ports eth_reset]
#
set_property PACKAGE_PIN J4 [get_ports eth_txen]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:220
# The conversion of 'IOSTANDARD' constraint on 'net' object 'eth_txen' has been applied to the port object 'eth_txen'.
set_property IOSTANDARD LVCMOS33 [get_ports eth_txen]
#
set_property PACKAGE_PIN M6 [get_ports eth_rxer]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:221
# The conversion of 'IOSTANDARD' constraint on 'net' object 'eth_rxer' has been applied to the port object 'eth_rxer'.
set_property IOSTANDARD LVCMOS33 [get_ports eth_rxer]

##USB-RS232 Interface
#
set_property PACKAGE_PIN U20 [get_ports UART_TXD]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:224
# The conversion of 'IOSTANDARD' constraint on 'net' object 'UART_TXD' has been applied to the port object 'UART_TXD'.
set_property IOSTANDARD LVCMOS33 [get_ports UART_TXD]
#
set_property PACKAGE_PIN V20 [get_ports RsRx]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:225
# The conversion of 'IOSTANDARD' constraint on 'net' object 'RsRx' has been applied to the port object 'RsRx'.
set_property IOSTANDARD LVCMOS33 [get_ports RsRx]

##Micro SD Connector
# XXX - No microSD connector on first revision PCBs.  Break out on an expansion connector somewhere?
# Broken out on TestPad1-TestPad5
#
set_property PACKAGE_PIN T16 [get_ports sdClock]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:230
# The conversion of 'IOSTANDARD' constraint on 'net' object 'sdClock' has been applied to the port object 'sdClock'.
set_property IOSTANDARD LVCMOS33 [get_ports sdClock]
#
set_property PACKAGE_PIN U16 [get_ports sdReset]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:231
# The conversion of 'IOSTANDARD' constraint on 'net' object 'sdReset' has been applied to the port object 'sdReset'.
set_property IOSTANDARD LVCMOS33 [get_ports sdReset]
#
set_property PACKAGE_PIN W16 [get_ports sdMISO]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:232
# The conversion of 'IOSTANDARD' constraint on 'net' object 'sdMISO' has been applied to the port object 'sdMISO'.
set_property IOSTANDARD LVCMOS33 [get_ports sdMISO]
#
set_property PACKAGE_PIN W15 [get_ports sdMOSI]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:233
# The conversion of 'IOSTANDARD' constraint on 'net' object 'sdMOSI' has been applied to the port object 'sdMOSI'.
set_property IOSTANDARD LVCMOS33 [get_ports sdMOSI]
#NET "sd_dat<0>"      LOC=T15 | IOSTANDARD=LVCMOS33; #
#NET "sd_dat<1>"      LOC= | IOSTANDARD=LVCMOS33; #
#NET "sd_dat<2>"      LOC= | IOSTANDARD=LVCMOS33; #
#NET "sd_dat<3>"      LOC= | IOSTANDARD=LVCMOS33; #

## Pmod Header JA
#NET "jalo<1>"          LOC= | IOSTANDARD=LVCMOS33; #
#NET "jalo<2>"          LOC= | IOSTANDARD=LVCMOS33; #
#NET "jalo<3>"          LOC= | IOSTANDARD=LVCMOS33; #
#NET "jalo<4>"          LOC= | IOSTANDARD=LVCMOS33; #
#NET "jahi<7>"          LOC= | IOSTANDARD=LVCMOS33; #
#NET "jahi<8>"          LOC= | IOSTANDARD=LVCMOS33; #
#NET "jahi<9>"          LOC= | IOSTANDARD=LVCMOS33; #
#NET "jahi<10>"         LOC= | IOSTANDARD=LVCMOS33; #

## Pmod Header JB
#NET "jblo<1>"          LOC= | IOSTANDARD=LVCMOS33; #
#NET "jblo<2>"          LOC= | IOSTANDARD=LVCMOS33; #
#NET "jblo<3>"          LOC= | IOSTANDARD=LVCMOS33; #
#NET "jblo<4>"          LOC= | IOSTANDARD=LVCMOS33; #
#NET "jbhi<7>"          LOC= | IOSTANDARD=LVCMOS33; #
#NET "jbhi<8>"          LOC= | IOSTANDARD=LVCMOS33; #
#NET "jbhi<9>"          LOC= | IOSTANDARD=LVCMOS33; #
#NET "jbhi<10>"         LOC= | IOSTANDARD=LVCMOS33; #

## Pmod Header JC
#NET "jclo<1>"          LOC= | IOSTANDARD=LVCMOS33; #
#NET "jclo<2>"          LOC= | IOSTANDARD=LVCMOS33; #
#NET "jc<3>"          LOC= | IOSTANDARD=LVCMOS33; #
#NET "jc<4>"          LOC= | IOSTANDARD=LVCMOS33; #
#NET "jc<7>"          LOC= | IOSTANDARD=LVCMOS33; #
#NET "jc<8>"          LOC= | IOSTANDARD=LVCMOS33; #
#NET "jc<9>"          LOC= | IOSTANDARD=LVCMOS33; #
#NET "jc<10>"         LOC= | IOSTANDARD=LVCMOS33; #

## FDC interface
# Output signals
#
set_property PACKAGE_PIN P6 [get_ports f_density]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:271
# The conversion of 'IOSTANDARD' constraint on 'net' object 'f_density' has been applied to the port object 'f_density'.
set_property IOSTANDARD LVCMOS33 [get_ports f_density]
#
set_property PACKAGE_PIN M5 [get_ports f_motor]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:272
# The conversion of 'IOSTANDARD' constraint on 'net' object 'f_motor' has been applied to the port object 'f_motor'.
set_property IOSTANDARD LVCMOS33 [get_ports f_motor]
#
set_property PACKAGE_PIN N5 [get_ports f_select]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:273
# The conversion of 'IOSTANDARD' constraint on 'net' object 'f_select' has been applied to the port object 'f_select'.
set_property IOSTANDARD LVCMOS33 [get_ports f_select]
#
set_property PACKAGE_PIN P5 [get_ports f_stepdir]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:274
# The conversion of 'IOSTANDARD' constraint on 'net' object 'f_stepdir' has been applied to the port object 'f_stepdir'.
set_property IOSTANDARD LVCMOS33 [get_ports f_stepdir]
#
set_property PACKAGE_PIN M3 [get_ports f_step]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:275
# The conversion of 'IOSTANDARD' constraint on 'net' object 'f_step' has been applied to the port object 'f_step'.
set_property IOSTANDARD LVCMOS33 [get_ports f_step]
#
set_property PACKAGE_PIN N4 [get_ports f_wdata]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:276
# The conversion of 'IOSTANDARD' constraint on 'net' object 'f_wdata' has been applied to the port object 'f_wdata'.
set_property IOSTANDARD LVCMOS33 [get_ports f_wdata]
#
set_property PACKAGE_PIN N3 [get_ports f_wgate]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:277
# The conversion of 'IOSTANDARD' constraint on 'net' object 'f_wgate' has been applied to the port object 'f_wgate'.
set_property IOSTANDARD LVCMOS33 [get_ports f_wgate]
#
set_property PACKAGE_PIN M1 [get_ports f_side1]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:278
# The conversion of 'IOSTANDARD' constraint on 'net' object 'f_side1' has been applied to the port object 'f_side1'.
set_property IOSTANDARD LVCMOS33 [get_ports f_side1]
# Input Signals
#
set_property PACKAGE_PIN M2 [get_ports f_index]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:280
# The conversion of 'IOSTANDARD' constraint on 'net' object 'f_index' has been applied to the port object 'f_index'.
set_property IOSTANDARD LVCMOS33 [get_ports f_index]
#
set_property PACKAGE_PIN N2 [get_ports f_track0]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:281
# The conversion of 'IOSTANDARD' constraint on 'net' object 'f_track0' has been applied to the port object 'f_track0'.
set_property IOSTANDARD LVCMOS33 [get_ports f_track0]
#
set_property PACKAGE_PIN P2 [get_ports f_writeprotect]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:282
# The conversion of 'IOSTANDARD' constraint on 'net' object 'f_writeprotect' has been applied to the port object 'f_writeprotect'.
set_property IOSTANDARD LVCMOS33 [get_ports f_writeprotect]
#
set_property PACKAGE_PIN P1 [get_ports f_rdata]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:283
# The conversion of 'IOSTANDARD' constraint on 'net' object 'f_rdata' has been applied to the port object 'f_rdata'.
set_property IOSTANDARD LVCMOS33 [get_ports f_rdata]
#
set_property PACKAGE_PIN R1 [get_ports f_diskchanged]
# /home/kdyke/Mega65.px100mhz/src/vhdl/mega65r1.ucf:284
# The conversion of 'IOSTANDARD' constraint on 'net' object 'f_diskchanged' has been applied to the port object 'f_diskchanged'.
set_property IOSTANDARD LVCMOS33 [get_ports f_diskchanged]



# XXX - Do we need something like this?
# CONFIG INTERNAL_VREF_BANK34= 0.900;

         
