#!/usr/bin/env python

from os.path import realpath, dirname, join
from sys import argv, path

path.insert(0, join(dirname(realpath(argv[0])), 'lib'))

import Ophis.Main

Ophis.Main.run_ophis(argv[1:])
